export default {
	index: 'Overview',
	'youtube-summarize-api': 'YouTube Summary API',
	'youtube-transcript-api': 'YouTube Transcript API',
	'youtube-stats-api': 'YouTube Stats API',
	'youtube-comments-api': 'YouTube Comments API',
	'tiktok-summarize-api': 'TikTok Summary API',
	'tiktok-transcript-api': 'TikTok Transcript API',
	'tiktok-stats-api': 'TikTok Stats API',
	'tiktok-comments-api': 'TikTok Comments API',
	'tiktok-channel-stats-api': 'TikTok Channel Stats API',
	'instagram-summarize-api': 'Instagram Summary API',
	'instagram-transcript-api': 'Instagram Transcript API',
	'instagram-stats-api': 'Instagram Stats API',
	'instagram-channel-stats-api': 'Instagram Channel Stats API',
	errors: 'Errors',
};
