export default {
	index: 'Overview',
	'openapi-playground': {
		title: 'Interactive Playground ↗',
		href: 'https://api.socialkit.dev/docs',
		newWindow: true,
	},
	'youtube-transcript-api': 'YouTube Transcript API',
	'youtube-summarize-api': 'YouTube Summary API',
	'youtube-stats-api': 'YouTube Stats API',
	'youtube-comments-api': 'YouTube Comments API',
	'youtube-channel-stats-api': 'YouTube Channel Stats API',
	'youtube-search-api': 'YouTube Search API',
	'youtube-videos-api': 'YouTube Videos API',
	'youtube-download-api': 'YouTube Video Download API',
	'async-download-api': 'Async Download API (v2)',
	'tiktok-transcript-api': 'TikTok Transcript API',
	'tiktok-summarize-api': 'TikTok Summary API',
	'tiktok-stats-api': 'TikTok Stats API',
	'tiktok-comments-api': 'TikTok Comments API',
	'tiktok-channel-stats-api': 'TikTok Channel Stats API',
	'tiktok-channel-videos-api': 'TikTok Channel Videos API',
	'tiktok-search-api': 'TikTok Search API',
	'tiktok-hashtag-search-api': 'TikTok Hashtag Search API',
	'tiktok-download-api': 'TikTok Video Download API',
	'instagram-transcript-api': 'Instagram Transcript API',
	'instagram-summarize-api': 'Instagram Summary API',
	'instagram-stats-api': 'Instagram Stats API',
	'instagram-comments-api': 'Instagram Comments API',
	'instagram-channel-stats-api': 'Instagram Channel Stats API',
	'instagram-channel-posts-api': 'Instagram Channel Posts API',
	'instagram-channel-reels-api': 'Instagram Channel Reels API',
	'instagram-reels-search-api': 'Instagram Reels Search API',
	'instagram-download-api': 'Instagram Video Download API',
	'facebook-transcript-api': 'Facebook Transcript API',
	'facebook-summarize-api': 'Facebook Summary API',
	'facebook-stats-api': 'Facebook Stats API',
	'facebook-comments-api': 'Facebook Comments API',
	'facebook-channel-stats-api': 'Facebook Channel Stats API',
	'twitter-profile-api': 'Twitter Profile API',
	'twitter-tweets-api': 'Twitter Tweets API',
	'twitter-tweet-api': 'Twitter Tweet API',
	'twitter-thread-api': 'Twitter Thread API',
	'twitter-transcript-api': 'Twitter Transcript API',
	'linkedin-profile-api': 'LinkedIn Profile API',
	'linkedin-company-api': 'LinkedIn Company API',
	'linkedin-company-posts-api': 'LinkedIn Company Posts API',
	'linkedin-post-api': 'LinkedIn Post API',
	'linkedin-transcript-api': 'LinkedIn Transcript API',
	'video-transcript-api': 'Video Transcript API',
	'video-summarize-api': 'Video Summary API',
	errors: 'Errors',
};
