export default {
	index: 'Overview',
	'youtube-transcript-api': 'YouTube Transcript API',
	'youtube-summarize-api': 'YouTube Summary API',
	'youtube-stats-api': 'YouTube Stats API',
	'youtube-comments-api': 'YouTube Comments API',
	'youtube-channel-stats-api': 'YouTube Channel Stats API',
	'youtube-search-api': 'YouTube Search API',
	'youtube-videos-api': 'YouTube Videos API',
	'youtube-download-api': 'YouTube Video Download API',
	'tiktok-transcript-api': 'TikTok Transcript API',
	'tiktok-summarize-api': 'TikTok Summary API',
	'tiktok-stats-api': 'TikTok Stats API',
	'tiktok-comments-api': 'TikTok Comments API',
	'tiktok-channel-stats-api': 'TikTok Channel Stats API',
	'tiktok-search-api': 'TikTok Search API',
	'tiktok-hashtag-search-api': 'TikTok Hashtag Search API',
	'instagram-transcript-api': 'Instagram Transcript API',
	'instagram-summarize-api': 'Instagram Summary API',
	'instagram-stats-api': 'Instagram Stats API',
	'instagram-channel-stats-api': 'Instagram Channel Stats API',
	'facebook-transcript-api': 'Facebook Transcript API',
	'facebook-summarize-api': 'Facebook Summary API',
	'facebook-stats-api': 'Facebook Stats API',
	'facebook-channel-stats-api': 'Facebook Channel Stats API',
	'video-transcript-api': 'Video Transcript API',
	'video-summarize-api': 'Video Summary API',
	errors: 'Errors',
};
